export interface SiteToTest {
  name: string;
  previewUrl: string;
  liveUrl: string;
  cookieSelector?: string;
  previewNewsUrl?: string;
  liveNewsUrl?: string;
  previewMatchesUrl?: string;
  liveMatchesUrl?: string;
  previewTeamsUrl?: string;
  liveTeamsUrl?: string;
}

export const sitesToTest: SiteToTest[] = [
  {
    name: "Mansfield Town",
    previewUrl: "https://livepreview.mansfieldtown.net/",
    liveUrl: "https://www.mansfieldtown.net/",
    previewNewsUrl: "https://livepreview.mansfieldtown.net/news",
    liveNewsUrl: "https://www.mansfieldtown.net/news",
    previewMatchesUrl: "https://livepreview.mansfieldtown.net/matches",
    liveMatchesUrl: "https://www.mansfieldtown.net/matches",
    previewTeamsUrl: "https://livepreview.mansfieldtown.net/teams",
    liveTeamsUrl: "https://www.mansfieldtown.net/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Morecambe FC",
    previewUrl: "https://livepreview.morecambefc.com/",
    liveUrl: "https://www.morecambefc.com/",
    previewNewsUrl: "https://livepreview.morecambefc.com/news",
    liveNewsUrl: "https://www.morecambefc.com/news",
    previewMatchesUrl: "https://livepreview.morecambefc.com/matches",
    liveMatchesUrl: "https://www.morecambefc.com/matches",
    previewTeamsUrl: "https://livepreview.morecambefc.com/teams",
    liveTeamsUrl: "https://www.morecambefc.com/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Crewe Alexandra FC",
    previewUrl: "https://livepreview.crewealex.net",
    liveUrl: "https://www.crewealex.net",
    previewNewsUrl: "https://livepreview.crewealex.net/news",
    liveNewsUrl: "https://www.crewealex.net/news",
    previewMatchesUrl: "https://livepreview.crewealex.net/matches",
    liveMatchesUrl: "https://www.crewealex.net/matches",
    previewTeamsUrl: "https://livepreview.crewealex.net/teams",
    liveTeamsUrl: "https://www.crewealex.net/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Cheltenham Town FC",
    previewUrl: "https://livepreview.ctfc.com/",
    liveUrl: "https://www.ctfc.com/",
    previewNewsUrl: "https://livepreview.ctfc.com/news",
    liveNewsUrl: "https://www.ctfc.com/news",
    previewMatchesUrl: "https://livepreview.ctfc.com/matches",
    liveMatchesUrl: "https://www.ctfc.com/matches",
    previewTeamsUrl: "https://livepreview.ctfc.com/teams",
    liveTeamsUrl: "https://www.ctfc.com/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Wrexham AFC",
    previewUrl: "https://livepreview.wrexhamafc.co.uk",
    liveUrl: "https://www.wrexhamafc.co.uk/",
    previewNewsUrl: "https://livepreview.wrexhamafc.co.uk/news",
    liveNewsUrl: "https://www.wrexhamafc.co.uk/news",
    previewMatchesUrl: "https://livepreview.wrexhamafc.co.uk/matches",
    liveMatchesUrl: "https://www.wrexhamafc.co.uk/matches",
    previewTeamsUrl: "https://livepreview.wrexhamafc.co.uk/teams",
    liveTeamsUrl: "https://www.wrexhamafc.co.uk/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Preston North End",
    previewUrl: "https://livepreview.pnefc.net/",
    liveUrl: "https://www.pnefc.net/",
    previewNewsUrl: "https://livepreview.pnefc.net/news",
    liveNewsUrl: "https://www.pnefc.net/news",
    previewMatchesUrl: "https://livepreview.pnefc.net/matches",
    liveMatchesUrl: "https://www.pnefc.net/matches",
    previewTeamsUrl: "https://livepreview.pnefc.net/teams",
    liveTeamsUrl: "https://www.pnefc.net/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Rotherham United FC",
    previewUrl: "https://livepreview.themillers.co.uk/",
    liveUrl: "https://www.themillers.co.uk/",
    previewNewsUrl: "https://livepreview.themillers.co.uk/news",
    liveNewsUrl: "https://www.themillers.co.uk/news",
    previewMatchesUrl: "https://livepreview.themillers.co.uk/matches",
    liveMatchesUrl: "https://www.themillers.co.uk/news",
    previewTeamsUrl: "https://livepreview.themillers.co.uk/teams",
    liveTeamsUrl: "https://www.themillers.co.uk/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Sheffield Wednesday FC",
    previewUrl: "https://livepreview.swfc.co.uk/",
    liveUrl: "https://www.swfc.co.uk/",
    previewNewsUrl: "https://livepreview.swfc.co.uk/news",
    liveNewsUrl: "https://www.swfc.co.uk/news",
    previewMatchesUrl: "https://livepreview.swfc.co.uk/matches",
    liveMatchesUrl: "https://www.swfc.co.uk/matches",
    previewTeamsUrl: "https://livepreview.swfc.co.uk/teams",
    liveTeamsUrl: "https://www.swfc.co.uk/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Watford FC",
    previewUrl: "https://livepreview.watfordfc.com/",
    liveUrl: "https://www.watfordfc.com/",
    previewNewsUrl: "https://livepreview.watfordfc.com/news",
    liveNewsUrl: "https://www.watfordfc.com/news",
    previewMatchesUrl: "https://livepreview.watfordfc.com/matches",
    liveMatchesUrl: "https://www.watfordfc.com/matches",
    previewTeamsUrl: "https://livepreview.watfordfc.com/teams",
    liveTeamsUrl: "https://www.watfordfc.com/matches",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Barnsley FC",
    previewUrl: "https://livepreview.barnsleyfc.co.uk/",
    liveUrl: "https://www.barnsleyfc.co.uk/",
    previewNewsUrl: "https://livepreview.barnsleyfc.co.uk/news",
    liveNewsUrl: "https://www.barnsleyfc.co.uk/news",
    previewMatchesUrl: "https://livepreview.barnsleyfc.co.uk/matches",
    liveMatchesUrl: "https://www.barnsleyfc.co.uk/matches",
    previewTeamsUrl: "https://livepreview.barnsleyfc.co.uk/teams",
    liveTeamsUrl: "https://www.barnsleyfc.co.uk/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Burton Albion FC",
    previewUrl: "https://livepreview.burtonalbionfc.co.uk/",
    liveUrl: "https://www.burtonalbionfc.co.uk/ ",
    previewNewsUrl: "https://livepreview.burtonalbionfc.co.uk/news",
    liveNewsUrl: "https://www.burtonalbionfc.co.uk/news",
    previewMatchesUrl: "https://livepreview.burtonalbionfc.co.uk/matches",
    liveMatchesUrl: "https://www.burtonalbionfc.co.uk/matches",
    previewTeamsUrl: "https://livepreview.burtonalbionfc.co.uk/teams",
    liveTeamsUrl: "https://www.burtonalbionfc.co.uk/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Northampton Town FC",
    previewUrl: "https://livepreview.ntfc.co.uk/",
    liveUrl: "https://www.ntfc.co.uk/",
    previewNewsUrl: "https://livepreview.ntfc.co.uk/news",
    liveNewsUrl: "https://www.ntfc.co.uk/news",
    previewMatchesUrl: "https://livepreview.ntfc.co.uk/matches",
    liveMatchesUrl: "https://www.ntfc.co.uk/matches",
    previewTeamsUrl: "https://livepreview.ntfc.co.uk/teams",
    liveTeamsUrl: "https://www.ntfc.co.uk/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Stevenage FC",
    previewUrl: "https://livepreview.stevenagefc.com/",
    liveUrl: "https://www.stevenagefc.com/",
    previewNewsUrl: "https://livepreview.stevenagefc.com/news",
    liveNewsUrl: "https://www.stevenagefc.com/news",
    previewMatchesUrl: "https://livepreview.stevenagefc.com/matches",
    liveMatchesUrl: "https://www.stevenagefc.com/matches",
    previewTeamsUrl: "https://livepreview.stevenagefc.com/teams",
    liveTeamsUrl: "https://www.stevenagefc.com/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Accrington Stanley FC",
    previewUrl: "https://livepreview.accringtonstanley.co.uk/",
    liveUrl: "https://www.accringtonstanley.co.uk/",
    previewNewsUrl: "https://livepreview.accringtonstanley.co.uk/news",
    liveNewsUrl: "https://www.accringtonstanley.co.uk/news",
    previewMatchesUrl: "https://livepreview.accringtonstanley.co.uk/matches",
    liveMatchesUrl: "https://www.accringtonstanley.co.uk/matches",
    previewTeamsUrl: "https://livepreview.accringtonstanley.co.uk/teams",
    liveTeamsUrl: "https://www.accringtonstanley.co.uk/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Barrow AFC",
    previewUrl: "https://livepreview.barrowafc.com/",
    liveUrl: "https://www.barrowafc.com/",
    previewNewsUrl: "https://livepreview.barrowafc.com/news",
    liveNewsUrl: "https://www.barrowafc.com/news",
    previewMatchesUrl: "https://livepreview.barrowafc.com/matches",
    liveMatchesUrl: "https://www.barrowafc.com/matches",
    previewTeamsUrl: "https://livepreview.barrowafc.com/teams",
    liveTeamsUrl: "https://www.barrowafc.com/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Crawley Town FC",
    previewUrl: "https://d3h8a6ibdavuib.cloudfront.net/",
    liveUrl: "https://www.crawleytownfc.com/",
    previewNewsUrl: "https://d3h8a6ibdavuib.cloudfront.net/news",
    liveNewsUrl: "https://www.crawleytownfc.com/news",
    previewMatchesUrl: "https://d3h8a6ibdavuib.cloudfront.net/matches",
    liveMatchesUrl: "https://www.crawleytownfc.com/matches",
    previewTeamsUrl: "https://d3h8a6ibdavuib.cloudfront.net/teams",
    liveTeamsUrl: "https://www.crawleytownfc.com/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Harrogate Town AFC",
    previewUrl: "https://livepreview.harrogatetownafc.com/",
    liveUrl: "https://www.harrogatetownafc.com/",
    previewNewsUrl: "https://livepreview.harrogatetownafc.com/news",
    liveNewsUrl: "https://www.harrogatetownafc.com/news",
    previewMatchesUrl: "https://livepreview.harrogatetownafc.com/matches",
    liveMatchesUrl: "https://www.harrogatetownafc.com/matches",
    previewTeamsUrl: "https://livepreview.harrogatetownafc.com/teams",
    liveTeamsUrl: "https://www.harrogatetownafc.com/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Milton Keynes Dons FC",
    previewUrl: "https://livepreview.mkdons.com/",
    liveUrl: "https://www.mkdons.com/",
    previewNewsUrl: "https://livepreview.mkdons.com/news",
    liveNewsUrl: "https://www.mkdons.com/news",
    previewMatchesUrl: "https://livepreview.mkdons.com/matches",
    liveMatchesUrl: "https://www.mkdons.com/matches",
    previewTeamsUrl: "https://livepreview.mkdons.com/teams",
    liveTeamsUrl: "https://www.mkdons.com/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Coventry City FC",
    previewUrl: "https://livepreview.ccfc.co.uk/",
    liveUrl: "https://www.ccfc.co.uk/",
    previewNewsUrl: "https://livepreview.ccfc.co.uk/news",
    liveNewsUrl: "https://www.ccfc.co.uk/news",
    previewMatchesUrl: "https://livepreview.ccfc.co.uk/matches",
    liveMatchesUrl: "https://www.ccfc.co.uk/matches",
    previewTeamsUrl: "https://livepreview.ccfc.co.uk/teams",
    liveTeamsUrl: "https://www.ccfc.co.uk/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Colchester United FC",
    previewUrl: "https://livepreview.cu-fc.com/",
    liveUrl: "https://www.cu-fc.com/",
    previewNewsUrl: "https://livepreview.cu-fc.com/news",
    liveNewsUrl: "https://www.cu-fc.com/news",
    previewMatchesUrl: "https://livepreview.cu-fc.com/matches",
    liveMatchesUrl: "https://www.cu-fc.com/matches",
    previewTeamsUrl: "https://livepreview.cu-fc.com/teams",
    liveTeamsUrl: "https://www.cu-fc.com/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Swindon Town FC",
    previewUrl: "https://livepreview.swindontownfc.co.uk/",
    liveUrl: "https://www.swindontownfc.co.uk/",
    previewNewsUrl: "https://livepreview.swindontownfc.co.uk/news",
    liveNewsUrl: "https://www.swindontownfc.co.uk/news",
    previewMatchesUrl: "https://livepreview.swindontownfc.co.uk/matches",
    liveMatchesUrl: "https://www.swindontownfc.co.uk/matches",
    previewTeamsUrl: "https://livepreview.swindontownfc.co.uk/teams",
    liveTeamsUrl: "https://www.swindontownfc.co.uk/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Shrewsbury Town FC",
    previewUrl: "https://livepreview.shrewsburytown.com/",
    liveUrl: "https://www.shrewsburytown.com/",
    previewNewsUrl: "https://livepreview.shrewsburytown.com/news",
    liveNewsUrl: "https://www.shrewsburytown.com/news",
    previewMatchesUrl: "https://livepreview.shrewsburytown.com/matches",
    liveMatchesUrl: "https://www.shrewsburytown.com/matches",
    previewTeamsUrl: "https://livepreview.shrewsburytown.com/teams",
    liveTeamsUrl: "https://www.shrewsburytown.com/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Everton FC",
    previewUrl: "https://livepreview.evertonfc.com/",
    liveUrl: "https://www.evertonfc.com/",
    previewNewsUrl: "https://livepreview.evertonfc.com/news",
    liveNewsUrl: "https://www.evertonfc.com/news",
    previewMatchesUrl: "https://livepreview.evertonfc.com/matches",
    liveMatchesUrl: "https://www.evertonfc.com/matches",
    previewTeamsUrl: "https://livepreview.evertonfc.com/teams",
    liveTeamsUrl: "https://www.evertonfc.com/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Fulham FC",
    previewUrl: "https://livepreview.fulhamfc.com/",
    liveUrl: "https://www.fulhamfc.com/",
    previewNewsUrl: "https://livepreview.fulhamfc.com/news",
    liveNewsUrl: "https://www.fulhamfc.com/news/",
    previewMatchesUrl: "https://livepreview.fulhamfc.com/matches",
    liveMatchesUrl: "https://www.fulhamfc.com/matches/",
    previewTeamsUrl: "https://livepreview.fulhamfc.com/teams",
    liveTeamsUrl: "https://www.fulhamfc.com/teams/",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Aston Villa F.C",
    previewUrl: "https://livepreview.avfc.co.uk/",
    liveUrl: "https://www.avfc.co.uk/",
    previewNewsUrl: "https://livepreview.avfc.co.uk/news/",
    liveNewsUrl: "https://www.avfc.co.uk/news/",
    previewMatchesUrl: "https://livepreview.avfc.co.uk/matches/",
    liveMatchesUrl: "https://www.avfc.co.uk/matches/",
    previewTeamsUrl: "https://livepreview.avfc.co.uk/teams/",
    liveTeamsUrl: "https://www.avfc.co.uk/teams/",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "AFC Bournemouth",
    previewUrl: "https://livepreview.afcb.co.uk/",
    liveUrl: "https://www.afcb.co.uk/",
    previewNewsUrl: "https://livepreview.afcb.co.uk/news",
    liveNewsUrl: "https://www.afcb.co.uk/news",
    previewMatchesUrl: "https://livepreview.afcb.co.uk/matches",
    liveMatchesUrl: "https://www.afcb.co.uk/matches",
    previewTeamsUrl: "https://livepreview.afcb.co.uk/teams",
    liveTeamsUrl: "https://www.afcb.co.uk/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Blackburn Rovers",
    previewUrl: "https://livepreview.rovers.co.uk/",
    liveUrl: "https://www.rovers.co.uk/",
    previewNewsUrl: "https://livepreview.rovers.co.uk/news",
    liveNewsUrl: "https://www.rovers.co.uk/news",
    previewMatchesUrl: "https://livepreview.rovers.co.uk/matches",
    liveMatchesUrl: "https://www.rovers.co.uk/matches",
    previewTeamsUrl: "https://livepreview.rovers.co.uk/teams",
    liveTeamsUrl: "https://www.rovers.co.uk/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Blackpool FC",
    previewUrl: "https://livepreview.blackpoolfc.co.uk/",
    liveUrl: "https://www.blackpoolfc.co.uk/",
    previewNewsUrl: "https://livepreview.blackpoolfc.co.uk/news",
    liveNewsUrl: "https://www.blackpoolfc.co.uk/news",
    previewMatchesUrl: "https://livepreview.blackpoolfc.co.uk/fixtures",
    liveMatchesUrl: "https://www.blackpoolfc.co.uk/fixtures",
    previewTeamsUrl: "https://livepreview.blackpoolfc.co.uk/squads",
    liveTeamsUrl: "https://www.blackpoolfc.co.uk/squads",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Hull City",
    previewUrl: "https://livepreview.wearehullcity.co.uk/",
    liveUrl: "https://www.wearehullcity.co.uk/",
    previewNewsUrl: "https://livepreview.wearehullcity.co.uk/news",
    liveNewsUrl: "https://www.wearehullcity.co.uk/news",
    previewMatchesUrl: "https://livepreview.wearehullcity.co.uk/matches",
    liveMatchesUrl: "https://www.wearehullcity.co.uk/matches",
    previewTeamsUrl: "https://livepreview.wearehullcity.co.uk/teams",
    liveTeamsUrl: "https://www.wearehullcity.co.uk/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Millwall FC",
    previewUrl: "https://livepreview.gc.millwallfcservices.co.uk/",
    liveUrl: "https://www.millwallfc.co.uk/",
    previewNewsUrl: "https://livepreview.gc.millwallfcservices.co.uk/news",
    liveNewsUrl: "https://www.millwallfc.co.uk/news",
    previewMatchesUrl: "https://livepreview.gc.millwallfcservices.co.uk/matches",
    liveMatchesUrl: "https://www.millwallfc.co.uk/matches",
    previewTeamsUrl: "https://livepreview.gc.millwallfcservices.co.uk/squads",
    liveTeamsUrl: "https://www.millwallfc.co.uk/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Portsmouth FC",
    previewUrl: "https://livepreview.portsmouthfc.co.uk/",
    liveUrl: "https://www.portsmouthfc.co.uk/",
    previewNewsUrl: "https://livepreview.portsmouthfc.co.uk/news",
    liveNewsUrl: "https://www.portsmouthfc.co.uk/news",
    previewMatchesUrl: "https://livepreview.portsmouthfc.co.uk/matches",
    liveMatchesUrl: "https://www.portsmouthfc.co.uk/matches",
    previewTeamsUrl: "https://livepreview.portsmouthfc.co.uk/teams",
    liveTeamsUrl: "https://www.portsmouthfc.co.uk/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Wycombe Wanderers",
    previewUrl: "https://livepreview.gc.wycombewanderersfcservices.co.uk/",
    liveUrl: "https://www.wwfc.com/",
    previewNewsUrl: "https://livepreview.gc.wycombewanderersfcservices.co.uk/news",
    liveNewsUrl: "https://www.wwfc.com/news",
    previewMatchesUrl: "https://livepreview.gc.wycombewanderersfcservices.co.uk/matches",
    liveMatchesUrl: "https://www.wwfc.com/matches",
    previewTeamsUrl: "https://livepreview.gc.wycombewanderersfcservices.co.uk/teams",
    liveTeamsUrl: "https://www.wwfc.com/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Bradford City AFC",
    previewUrl: "https://livepreview.bradfordcityafc.com/",
    liveUrl: "https://www.bradfordcityafc.com/",
    previewNewsUrl: "https://livepreview.bradfordcityafc.com/news",
    liveNewsUrl: "https://www.bradfordcityafc.com/news",
    previewMatchesUrl: "https://livepreview.bradfordcityafc.com/matches",
    liveMatchesUrl: "https://www.bradfordcityafc.com/matches",
    previewTeamsUrl: "https://livepreview.bradfordcityafc.com/teams",
    liveTeamsUrl: "https://www.bradfordcityafc.com/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Doncaster Rover FC",
    previewUrl: "https://livepreview.doncasterroversfc.co.uk/",
    liveUrl: "https://www.doncasterroversfc.co.uk/",
    previewNewsUrl: "https://livepreview.doncasterroversfc.co.uk/news",
    liveNewsUrl: "https://www.doncasterroversfc.co.uk/news",
    previewMatchesUrl: "https://livepreview.doncasterroversfc.co.uk/matches",
    liveMatchesUrl: "https://www.doncasterroversfc.co.uk/matches",
    previewTeamsUrl: "https://livepreview.doncasterroversfc.co.uk/teams",
    liveTeamsUrl: "https://www.doncasterroversfc.co.uk/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Hibs FC",
    previewUrl: "https://livepreview.hibernianfc.co.uk/",
    liveUrl: "https://www.hibernianfc.co.uk/",
    previewNewsUrl: "https://livepreview.hibernianfc.co.uk/news/",
    liveNewsUrl: "https://www.hibernianfc.co.uk/news",
    previewMatchesUrl: "https://livepreview.hibernianfc.co.uk/matches",
    liveMatchesUrl: "https://www.hibernianfc.co.uk/matches",
    previewTeamsUrl: "https://livepreview.hibernianfc.co.uk/teams",
    liveTeamsUrl: "https://www.hibernianfc.co.uk/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Leyton Orient FC",
    previewUrl: "https://livepreview.leytonorient.com/",
    liveUrl: "https://www.leytonorient.com/",
    previewNewsUrl: "https://livepreview.leytonorient.com/news",
    liveNewsUrl: "https://www.leytonorient.com/news",
    previewMatchesUrl: "https://livepreview.leytonorient.com/matches",
    liveMatchesUrl: "https://www.leytonorient.com/matches",
    previewTeamsUrl: "https://livepreview.leytonorient.com/teams",
    liveTeamsUrl: "https://www.leytonorient.com/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Middlesbrough FC",
    previewUrl: "https://livepreview.gc.middlesbroughfcservices.co.uk/",
    liveUrl: "https://www.mfc.co.uk/",
    previewNewsUrl: "https://livepreview.gc.middlesbroughfcservices.co.uk/news",
    liveNewsUrl: "https://www.mfc.co.uk/news",
    previewMatchesUrl: "https://livepreview.gc.middlesbroughfcservices.co.uk/matches",
    liveMatchesUrl: "https://www.mfc.co.uk/matches",
    previewTeamsUrl: "https://livepreview.gc.middlesbroughfcservices.co.uk/teams",
    liveTeamsUrl: "https://www.mfc.co.uk/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Notts County FC",
    previewUrl: "https://livepreview.nottscountyfc.co.uk/",
    liveUrl: "https://www.nottscountyfc.co.uk/",
    previewNewsUrl: "https://livepreview.nottscountyfc.co.uk/news",
    liveNewsUrl: "https://www.nottscountyfc.co.uk/news",
    previewMatchesUrl: "https://livepreview.nottscountyfc.co.uk/matches",
    liveMatchesUrl: "https://www.nottscountyfc.co.uk/matches",
    previewTeamsUrl: "https://livepreview.nottscountyfc.co.uk/teams",
    liveTeamsUrl: "https://www.nottscountyfc.co.uk/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Oldham Athletic A.F.C",
    previewUrl: "https://livepreview.oldhamathletic.co.uk/",
    liveUrl: "https://www.oldhamathletic.co.uk/",
    previewNewsUrl: "https://livepreview.oldhamathletic.co.uk/news",
    liveNewsUrl: "https://www.oldhamathletic.co.uk/news",
    previewMatchesUrl: "https://livepreview.oldhamathletic.co.uk/matches",
    liveMatchesUrl: "https://www.oldhamathletic.co.uk/matches",
    previewTeamsUrl: "https://livepreview.oldhamathletic.co.uk/teams",
    liveTeamsUrl: "https://www.oldhamathletic.co.uk/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Salford City FC",
    previewUrl: "https://livepreview.salfordcityfc.co.uk/",
    liveUrl: "https://www.salfordcityfc.co.uk/",
    previewNewsUrl: "https://livepreview.salfordcityfc.co.uk/news",
    liveNewsUrl: "https://www.salfordcityfc.co.uk/news",
    previewMatchesUrl: "https://livepreview.salfordcityfc.co.uk/matches",
    liveMatchesUrl: "https://www.salfordcityfc.co.uk/matches",
    previewTeamsUrl: "https://livepreview.salfordcityfc.co.uk/teams",
    liveTeamsUrl: "https://www.salfordcityfc.co.uk/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Southend United",
    previewUrl: "https://livepreview.southendunited.co.uk/",
    liveUrl: "https://www.southendunited.co.uk/",
    previewNewsUrl: "https://livepreview.southendunited.co.uk/news",
    liveNewsUrl: "https://www.southendunited.co.uk/news",
    previewMatchesUrl: "https://livepreview.southendunited.co.uk/matches",
    liveMatchesUrl: "https://www.southendunited.co.uk/matches",
    previewTeamsUrl: "https://livepreview.southendunited.co.uk/teams",
    liveTeamsUrl: "https://www.southendunited.co.uk/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Tranmere Rovers FC",
    previewUrl: "https://livepreview.tranmererovers.co.uk/",
    liveUrl: "https://www.tranmererovers.co.uk/",
    previewNewsUrl: "https://livepreview.tranmererovers.co.uk/news",
    liveNewsUrl: "https://www.tranmererovers.co.uk/news",
    previewMatchesUrl: "https://livepreview.tranmererovers.co.uk/matches",
    liveMatchesUrl: "https://www.tranmererovers.co.uk/matches",
    previewTeamsUrl: "https://livepreview.tranmererovers.co.uk/teams",
    liveTeamsUrl: "https://www.tranmererovers.co.uk/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Walsall FC",
    previewUrl: "https://livepreview.saddlers.co.uk/",
    liveUrl: "https://www.saddlers.co.uk/",
    previewNewsUrl: "https://livepreview.saddlers.co.uk/news",
    liveNewsUrl: "https://www.saddlers.co.uk/news",
    previewMatchesUrl: "https://livepreview.saddlers.co.uk/matches",
    liveMatchesUrl: "https://www.saddlers.co.uk/matches",
    previewTeamsUrl: "https://livepreview.saddlers.co.uk/teams",
    liveTeamsUrl: "https://www.saddlers.co.uk/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Reading FC",
    previewUrl: "https://livepreview.gc.readingfcservices.co.uk/",
    liveUrl: "https://www.readingfc.co.uk/",
    previewNewsUrl: "https://livepreview.gc.readingfcservices.co.uk/news/",
    liveNewsUrl: "https://www.readingfc.co.uk/news/",
    previewMatchesUrl: "https://livepreview.gc.readingfcservices.co.uk/matches/",
    liveMatchesUrl: "https://www.readingfc.co.uk/matches/",
    previewTeamsUrl: "https://livepreview.gc.readingfcservices.co.uk/teams/",
    liveTeamsUrl: "https://www.readingfc.co.uk/teams/",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Warrington Wolves",
    previewUrl: "https://livepreview.gc.warringtonwolves.com/",
    liveUrl: "https://warringtonwolves.com/",
    previewNewsUrl: "https://livepreview.gc.warringtonwolves.com/news/",
    liveNewsUrl: "https://warringtonwolves.com/news",
    previewMatchesUrl: "https://livepreview.gc.warringtonwolves.com/matches/",
    liveMatchesUrl: "https://warringtonwolves.com/matches/",
    previewTeamsUrl: "https://livepreview.gc.warringtonwolves.com/teams/",
    liveTeamsUrl: "https://warringtonwolves.com/teams/",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Wigan Athletic",
    previewUrl: "https://preview.wiganathletic.com/",
    liveUrl: "https://wiganathletic.com/",
    previewNewsUrl: "https://preview.wiganathletic.com/news",
    liveNewsUrl: "https://wiganathletic.com/news/",
    previewMatchesUrl: "https://preview.wiganathletic.com/matches",
    liveMatchesUrl: "https://wiganathletic.com/matches/",
    previewTeamsUrl: "https://preview.wiganathletic.com/teams",
    liveTeamsUrl: "https://wiganathletic.com/teams/",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Sheffield United F.C.",
    previewUrl: "https://livepreview.gc.sufc.co.uk/",
    liveUrl: "https://www.sufc.co.uk/",
    previewNewsUrl: "https://livepreview.gc.sufc.co.uk/news",
    liveNewsUrl: "https://www.sufc.co.uk/news",
    previewMatchesUrl: "https://livepreview.gc.sufc.co.uk/matches",
    liveMatchesUrl: "https://www.sufc.co.uk/matches",
    previewTeamsUrl: "https://livepreview.gc.sufc.co.uk/teams",
    liveTeamsUrl: "https://www.sufc.co.uk/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
    {
    name: "AFC Wimbledon",
    previewUrl: "https://livepreview.afcwimbledon.co.uk/",
    liveUrl: "https://www.afcwimbledon.co.uk/",
    previewNewsUrl: "https://livepreview.afcwimbledon.co.uk/news",
    liveNewsUrl: "https://www.afcwimbledon.co.uk/news",
    previewMatchesUrl: "https://livepreview.afcwimbledon.co.uk/matches",
    liveMatchesUrl: "https://www.afcwimbledon.co.uk/matches",
    previewTeamsUrl: "https://livepreview.afcwimbledon.co.uk/teams",
    liveTeamsUrl: "https://www.afcwimbledon.co.uk/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Ipswich Town FC",
    previewUrl: "https://livepreview.itfc.co.uk/",
    liveUrl: "https://www.itfc.co.uk/",
    previewNewsUrl: "https://livepreview.itfc.co.uk/news",
    liveNewsUrl: "https://www.itfc.co.uk/news",
    previewMatchesUrl: "https://livepreview.itfc.co.uk/matches",
    liveMatchesUrl: "https://www.itfc.co.uk/matches",
    previewTeamsUrl: "https://livepreview.itfc.co.uk/teams",
    liveTeamsUrl: "https://www.itfc.co.uk/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Nottm Forest",
    previewUrl: "https://livepreview.nottinghamforest.co.uk/",
    liveUrl: "https://www.nottinghamforest.co.uk/",
    previewNewsUrl: "https://livepreview.nottinghamforest.co.uk/news/",
    liveNewsUrl: "https://www.nottinghamforest.co.uk/news/",
    previewMatchesUrl: "https://livepreview.nottinghamforest.co.uk/matches/",
    liveMatchesUrl: "https://www.nottinghamforest.co.uk/matches/",
    previewTeamsUrl: "https://livepreview.nottinghamforest.co.uk/tteams/",
    liveTeamsUrl: "https://www.nottinghamforest.co.uk/teams/",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
  {
    name: "Sunderland",
    previewUrl: "https://livepreview.safc.com/",
    liveUrl: "https://www.safc.com/",
    previewNewsUrl: "https://livepreview.safc.com/news",
    liveNewsUrl: "https://www.safc.com/news",
    previewMatchesUrl: "https://livepreview.safc.com/matches",
    liveMatchesUrl: "https://www.safc.com/matches",
    previewTeamsUrl: "https://livepreview.safc.com/teams",
    liveTeamsUrl: "https://www.safc.com/teams",
    cookieSelector: '#onetrust-accept-btn-handler',
  },
];
